# general settings
name: ASSANet_32C6G4B_x3_FFT_b32_DF2K
model_type: SRModel
scale: 3
num_gpu: auto
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    dataroot_gt: /data0/SISR_dataset/DF2K/DF2K_train_HR_sub
    dataroot_lq: /data0/SISR_dataset/DF2K/DF2K_train_LR_bicubic/X3_sub
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 144
    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 16
    batch_size_per_gpu: 8
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  # --- validation
  val_1:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /data0/SISR_dataset/Benchmarks/Set5/HR
    dataroot_lq: /data0/SISR_dataset/Benchmarks/Set5/LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /data0/SISR_dataset/Benchmarks/Set14/HR
    dataroot_lq: /data0/SISR_dataset/Benchmarks/Set14/LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk

  val_3:
    name: B100
    type: PairedImageDataset
    dataroot_gt: /data0/SISR_dataset/Benchmarks/B100/HR
    dataroot_lq: /data0/SISR_dataset/Benchmarks/B100/LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk

  val_4:
    name: Urban100
    type: PairedImageDataset
    dataroot_gt: /data0/SISR_dataset/Benchmarks/Urban100/HR
    dataroot_lq: /data0/SISR_dataset/Benchmarks/Urban100/LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk

  val_5:
    name: Manga109
    type: PairedImageDataset
    dataroot_gt: /data0/SISR_dataset/Benchmarks/Manga109/HR
    dataroot_lq: /data0/SISR_dataset/Benchmarks/Manga109/LR_bicubic/X3
    filename_tmpl: '{}x3'
    io_backend:
      type: disk


# network structures
# Large Setting: 90C-6G-4B-2FFNExpansion
network_g:
  type: ASSANet
  dim: 32
  num_blocks: 4
  num_layers: 6
  upscale: 3
  num_heads: 1
  ffn_expansion_factor: 2.0
  img_range: 1.
  tlc_flag: True
  tlc_kernel: 48
  activation: 'relu'

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# all the training settings are based on SwinIR except for learning rate
# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  total_iter: 500000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  fft_opt:
    type: FFTLoss
    loss_weight: 0.05
    reduction: mean

# validation settings
val:
  val_freq: !!float 1e4
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true

# logging settings
logger:
  print_freq: 2000
  save_checkpoint_freq: !!float 1e4
  use_tb_logger: true

# dist training settings
dist_params:
  backend: nccl
  port: 29500